export const cities = [
  { en: "Tehran", fa: "تهران" },
  { en: "Mashhad", fa: "مشهد" },
  { en: "Isfahan", fa: "اصفهان" },
  { en: "Karaj", fa: "کرج" },
  { en: "Shiraz", fa: "شیراز" },
  { en: "Tabriz", fa: "تبریز" },
  { en: "Qom", fa: "قم" },
  { en: "Ahvaz", fa: "اهواز" },
  { en: "Kermanshah", fa: "کرمانشاه" },
  { en: "Urmia", fa: "ارومیه" },
  { en: "Rasht", fa: "رشت" },
  { en: "Zahedan", fa: "زاهدان" },
  { en: "Kerman", fa: "کرمان" },
  { en: "Arak", fa: "اراک" },
  { en: "Hamedan", fa: "همدان" },
  { en: "Yazd", fa: "یزد" },
  { en: "Ardabil", fa: "اردبیل" },
  { en: "Bandar Abbas", fa: "بندرعباس" },
  { en: "Qazvin", fa: "قزوین" },
  { en: "Zanjan", fa: "زنجان" },
  { en: "Sari", fa: "ساری" },
  { en: "Gorgan", fa: "گرگان" },
  { en: "Khorramabad", fa: "خرم‌آباد" },
  { en: "Sanandaj", fa: "سنندج" },
  { en: "Semnan", fa: "سمنان" },
  { en: "Shahrekord", fa: "شهرکرد" },
  { en: "Birjand", fa: "بیرجند" },
  { en: "Bushehr", fa: "بوشهر" },
  { en: "Ilam", fa: "ایلام" },
  { en: "Bojnord", fa: "بجنورد" },
  { en: "Yasuj", fa: "یاسوج" },
];
